<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $fillable = [
		'id',
		'user_id',
        'employee_id',
        'last_name', 
        'first_name', 
        'middle_name',
        'birthdate', 
        'gender',
        'status', 
        'address',
       	'country_city',   
        'zip_code',
        'telephone_no',
        'mobile_no',
        'email',
        'department', 
        'employment_type',
        'position',  
        'rank', 
        'work',
        'location',
        'cost_center',
        'payroll_group',
        'payment',
        'method',  
        'bank',   
        'bank_type',
        'bank_account_no',
        'date_hired',
        'date_ended',  
        'tax',
        'TIN',
        'RDO',
        'SSS',
        'HDMF',
        'Philhealth',
        'leave_approval_group',
        'timesheet_approval_group',
        'OT_approval_group',
        'expense_approval_group',
        'loan_approval_group',
        'deduct_SSS_contribution',   
        'fixed_SSS_amount',    
        'deduct_HDMF_contribution',  
        'fixed_HDMF_amount',  
        'deduct_philhealth_contribution',
        'fixed_philhealth_amount', 
        'basic_pay_amount',    
        'pay_rate_type',   
        'timesheet_required',
        'entitled_to_overtime', 
        'entitled_night_differential',    
        'entitled_unworked_regular_holiday_pay',  
        'entitled_unworked_special_holiday_pay', 
        'entitled_holiday_premium_pay',
        'entitled_rest_day_pay',
        'withholding_tax_type',    
        'expanded_withholding_tax_rate',
        'entitled_deminimis', 
        'active',
        'photo',
        'created_by',
        'updated_by',
    ];
}
